steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', '${_IMAGE}', '.']

images:
- '${_IMAGE}'

substitutions:
  _IMAGE: 'europe-west1-docker.pkg.dev/investor-recommender/portfolio/portfolio-app:latest'
